In [8]:
import numpy as np

zeros

In [9]:
ar_zero = np.zeros(5)
ar_zero

array([0., 0., 0., 0., 0.])

ones

In [10]:
ar_ones = np.ones(5)
ar_ones

array([1., 1., 1., 1., 1.])

empty

In [11]:
emt = np.empty(5)
print(emt.ndim)
emt

1


array([1., 1., 1., 1., 1.])

range

In [5]:
ran = np.arange(4)
ran

array([0, 1, 2, 3])

diagnonal

In [6]:
d = np.eye(3,5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

linspace

In [12]:
lin = np.linspace(0,20,num=5)
lin

array([ 0.,  5., 10., 15., 20.])